import { motion, useReducedMotion } from 'framer-motion';
import { FiFilter, FiSearch } from 'react-icons/fi';
import { EmptyState } from './States';

export default function DataTable({ columns, rows, renderActions, emptyMessage = 'No records found.', searchValue = '', onSearchChange, loadedCount = rows.length }) {
  const reducedMotion = useReducedMotion();
  return <div className="admin-panel ad:overflow-hidden ad:rounded-[26px] ad:border ad:border-slate-100 ad:bg-white">
    <div className="ad:flex ad:flex-wrap ad:items-center ad:justify-between ad:gap-4 ad:border-b ad:border-slate-100 ad:px-5 ad:py-5 ad:sm:px-6"><div><h3 className="ad:m-0 ad:text-base ad:font-semibold ad:text-slate-900">Records</h3><p className="ad:mt-1 ad:mb-0 ad:text-xs ad:text-slate-500">{rows.length} shown from {loadedCount} on this page</p></div>{onSearchChange && <div className="ad:flex ad:w-full ad:flex-wrap ad:items-center ad:gap-3 ad:sm:w-auto"><label className="ad:flex ad:min-w-[170px] ad:flex-1 ad:items-center ad:gap-2 ad:rounded-xl ad:border ad:border-slate-200 ad:bg-slate-50/70 ad:px-3 ad:transition-colors ad:focus-within:border-rose-300 ad:focus-within:bg-white ad:focus-within:ring-2 ad:focus-within:ring-rose-100 ad:sm:w-64"><FiSearch size={16} className="ad:shrink-0 ad:text-slate-400" /><input type="search" aria-label="Search this page" placeholder="Search this page" value={searchValue} onChange={(event) => onSearchChange(event.target.value)} className="ad:w-full ad:border-0 ad:bg-transparent ad:py-2.5 ad:text-sm ad:outline-none" /></label><span title="Search applies to the loaded page only" className="ad:inline-flex ad:items-center ad:gap-2 ad:rounded-xl ad:bg-rose-50 ad:px-3 ad:py-2.5 ad:text-xs ad:font-medium ad:text-rose-600"><FiFilter size={15} />Current page</span></div>}</div>
    {rows.length ? <div className="admin-table-scroll ad:overflow-x-auto"><table className="ad:w-full ad:min-w-[720px] ad:text-left ad:text-sm"><thead className="ad:bg-[#faf8fa] ad:text-[11px] ad:font-bold ad:uppercase ad:tracking-[.12em] ad:text-slate-500"><tr>{columns.map((column) => <th key={column.key} scope="col" className="ad:border-b ad:border-slate-200 ad:px-5 ad:py-4 ad:font-semibold">{column.label}</th>)}{renderActions && <th scope="col" className="ad:sticky ad:right-0 ad:z-10 ad:min-w-[170px] ad:border-b ad:border-l ad:border-slate-200 ad:bg-[#faf8fa] ad:px-5 ad:py-4 ad:text-right ad:font-semibold">Actions</th>}</tr></thead><tbody>{rows.map((row, index) => <motion.tr key={row.id ?? index} initial={reducedMotion ? false : { opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} whileHover={reducedMotion ? undefined : { y: -1 }} transition={{ duration: 0.2, delay: Math.min(index, 7) * 0.035 }} className="admin-data-row ad:border-t ad:border-slate-100">{columns.map((column) => <td key={column.key} className="ad:max-w-[320px] ad:px-5 ad:py-[18px] ad:text-slate-700">{column.render ? column.render(row) : row[column.key] ?? '—'}</td>)}{renderActions && <td className="admin-actions-cell ad:sticky ad:right-0 ad:z-10 ad:border-l ad:border-slate-100 ad:bg-white ad:px-4 ad:py-3 ad:text-right"><div className="ad:flex ad:items-center ad:justify-end ad:gap-2">{renderActions(row)}</div></td>}</motion.tr>)}</tbody></table></div> : <EmptyState title={searchValue ? 'No matching records' : emptyMessage} message={searchValue ? 'Try another term. Search covers only this loaded page.' : 'When records are available, they will appear here.'} />}
  </div>;
}
